Repository awslabs/dynein, pull requests merged in 2024-04, with the labels that each got.

#190 feat: implement new options into bwrite command
  .github/workflows/ci.yml
  README.md
  src/batch.rs
  src/bootstrap.rs
  src/cmd.rs
  src/data.rs
  src/main.rs
  src/parser.rs
  tests/bwrite.rs
  tests/cmd/bwrite.md
  tests/cmd_windows/bwrite.md
  tests/resources/test_batch_write_delete.json
  tests/resources/test_batch_write_put.json
  tests/resources/test_batch_write_put_delete.json
  tests/resources/test_batch_write_put_delete_multiple_tables.json
  tests/resources/test_batch_write_put_output.json
  tests/util/mod.rs
Labels: enhancement

#187 feat!: improve query to support dynein format
  README.md
  docs/query.md
  src/app.rs
  src/cmd.rs
  src/data.rs
  src/expression.pest
  src/main.rs
  src/parser.rs
  tests/cmd/query.md
  tests/cmd_windows/query.md
  tests/config.rs
  tests/query.rs
Labels: enhancement

#212 chore: add GitHub workflow for PR audit
  .github/workflows/ci.yml
Labels: tool

#214 chore: remove build-dependencies
  Cargo.lock
  Cargo.toml
Labels: maintenance

#211 chore: add an GitHub workflow for daily audit
  .github/workflows/audit.yml
Labels: tool

#208 chore!: update deps including major changes
  Cargo.lock
  Cargo.toml
  src/batch.rs
  src/transfer.rs
  tests/admin_desc.rs
  tests/config.rs
  tests/desc.rs
Labels: maintenance
